<a href="https://colab.research.google.com/github/LavanyaPobbathi/Machine-Learning-Projects/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
# Importing the dataset
dataset = pd.read_csv('Multiple-Linear-Dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values


In [ ]:
#OneHotEncoder is used to further transform the encoded categorical variable into multiple binary variables.
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categories='auto')
X = onehotencoder.fit_transform(X).toarray()


In [ ]:
# Avoiding the Dummy Variable Trap to avoid multicollinearity, its necessary When using one-hot encoding
X = X[:, 1:]


In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)


LinearRegression()

In [ ]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([102284.64605183, 133873.92383812, 134182.1495165 ,  73701.1069363 ,
       180642.25299736, 114717.24903894,  68335.07575312,  97433.45922275,
       114580.92136452, 170343.31979498])

In [ ]:
# Building the optimal model using Backward Elimination
#its a method to remove statistically insignificant features from the model.
import statsmodels.api as sm
X = np.append(arr=np.ones((50, 1)).astype(int), values=X, axis=1)
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
#endog = dependent variable (y), and exog = independent variables (X_opt).
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
#it provides the summary of the regression model, including coefficients, p-values, R-squared value
regressor_OLS.summary()



<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.203
Model:                            OLS   Adj. R-squared:                  0.113
Method:                 Least Squares   F-statistic:                     2.244
Date:                Mon, 12 Jun 2023   Prob (F-statistic):             0.0665
Time:                        20:50:04   Log-Likelihood:                -594.98
No. Observations:                  50   AIC:                             1202.
Df Residuals:                      44   BIC:                             1213.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.178e+05   5659.867     20.808      0.000    1.06e+05    1.29e+05
x1         -8.209e+04   3.84e+04     -2.139      0.038   -1.59e+05   -4730.369
x2         -5.284e+04   3.84e+04     -1.377      0.176    -1.3e+05    2.45e+04
x3         -6.828e+04   3.84e+04     -1.779      0.082   -1.46e+05    9086.971
x4         -4.801e+04   3.84e+04     -1.251      0.218   -1.25e+05    2.94e+04
x5         -3.654e+04   3.84e+04     -0.952      0.346   -1.14e+05    4.08e+04
==============================================================================
Omnibus:                        1.590   Durbin-Watson:                   0.512
Prob(Omnibus):                  0.452   Jarque-Bera (JB):                0.795
Skew:                          -0.059   Prob(JB):                        0.672
Kurtosis:                       3.606   Cond. No.                         7.47
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
X_opt = X[:, [0, 1, 3, 4, 5]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit() #sm.OLS is used to perform ordinary least squares regression.
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.169
Model:                            OLS   Adj. R-squared:                  0.095
Method:                 Least Squares   F-statistic:                     2.286
Date:                Mon, 12 Jun 2023   Prob (F-statistic):             0.0747
Time:                        20:50:04   Log-Likelihood:                -596.03
No. Observations:                  50   AIC:                             1202.
Df Residuals:                      45   BIC:                             1212.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.166e+05   5653.397     20.628      0.000    1.05e+05    1.28e+05
x1         -8.095e+04   3.88e+04     -2.089      0.042   -1.59e+05   -2883.631
x2         -6.713e+04   3.88e+04     -1.732      0.090   -1.45e+05    1.09e+04
x3         -4.686e+04   3.88e+04     -1.209      0.233   -1.25e+05    3.12e+04
x4         -3.539e+04   3.88e+04     -0.913      0.366   -1.13e+05    4.27e+04
==============================================================================
Omnibus:                        0.992   Durbin-Watson:                   0.475
Prob(Omnibus):                  0.609   Jarque-Bera (JB):                0.329
Skew:                          -0.022   Prob(JB):                        0.848
Kurtosis:                       3.395   Cond. No.                         7.38
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
X_opt = X[:, [0, 3, 4, 5]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.088
Model:                            OLS   Adj. R-squared:                  0.029
Method:                 Least Squares   F-statistic:                     1.486
Date:                Mon, 12 Jun 2023   Prob (F-statistic):              0.231
Time:                        20:50:04   Log-Likelihood:                -598.34
No. Observations:                  50   AIC:                             1205.
Df Residuals:                      46   BIC:                             1212.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.149e+05   5793.703     19.831      0.000    1.03e+05    1.27e+05
x1         -6.541e+04   4.01e+04     -1.629      0.110   -1.46e+05    1.54e+04
x2         -4.514e+04   4.01e+04     -1.125      0.267   -1.26e+05    3.57e+04
x3         -3.367e+04   4.01e+04     -0.839      0.406   -1.14e+05    4.71e+04
==============================================================================
Omnibus:                        0.598   Durbin-Watson:                   0.208
Prob(Omnibus):                  0.742   Jarque-Bera (JB):                0.133
Skew:                          -0.075   Prob(JB):                        0.935
Kurtosis:                       3.203   Cond. No.                         7.30
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
X_opt = X[:, [0, 3, 5]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.063
Model:                            OLS   Adj. R-squared:                  0.023
Method:                 Least Squares   F-statistic:                     1.588
Date:                Mon, 12 Jun 2023   Prob (F-statistic):              0.215
Time:                        20:50:04   Log-Likelihood:                -599.02
No. Observations:                  50   AIC:                             1204.
Df Residuals:                      47   BIC:                             1210.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.14e+05   5749.145     19.821      0.000    1.02e+05    1.26e+05
x1         -6.447e+04   4.02e+04     -1.602      0.116   -1.45e+05    1.65e+04
x2         -3.273e+04   4.02e+04     -0.813      0.420   -1.14e+05    4.82e+04
==============================================================================
Omnibus:                        0.287   Durbin-Watson:                   0.140
Prob(Omnibus):                  0.866   Jarque-Bera (JB):                0.017
Skew:                          -0.031   Prob(JB):                        0.992
Kurtosis:                       3.065   Cond. No.                         7.22
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
X_opt = X[:, [0, 3]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.050
Model:                            OLS   Adj. R-squared:                  0.030
Method:                 Least Squares   F-statistic:                     2.532
Date:                Mon, 12 Jun 2023   Prob (F-statistic):              0.118
Time:                        20:50:04   Log-Likelihood:                -599.37
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      48   BIC:                             1207.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.133e+05   5670.069     19.980      0.000    1.02e+05    1.25e+05
x1          -6.38e+04   4.01e+04     -1.591      0.118   -1.44e+05    1.68e+04
==============================================================================
Omnibus:                        0.164   Durbin-Watson:                   0.114
Prob(Omnibus):                  0.921   Jarque-Bera (JB):                0.001
Skew:                           0.009   Prob(JB):                         1.00
Kurtosis:                       2.989   Cond. No.                         7.15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

1. Two input features (Product_3 and Location); 1 output represents the estimated profit based on these two features.

In [ ]:
X = dataset[['Product_3', 'Location']].values
y = dataset['Profit'].values
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred

array([102284.64605183, 133873.92383812, 134182.1495165 ,  73701.1069363 ,
       180642.25299736, 114717.24903894,  68335.07575312,  97433.45922275,
       114580.92136452, 170343.31979498])

In [ ]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

2. Two input features (Product_1 and Product_3); 1 output represents the estimated profit based on these two features.


In [ ]:
X = dataset[['Product_1', 'Product_3']].values
y = dataset['Profit'].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred


array([102284.64605183, 133873.92383812, 134182.1495165 ,  73701.1069363 ,
       180642.25299736, 114717.24903894,  68335.07575312,  97433.45922275,
       114580.92136452, 170343.31979498])

In [ ]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])